<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\UmkReference;

class UmkReferenceSeeder extends Seeder
{
    /**
     * Seed 514 Official Indonesian Regencies/Cities UMK 2026 Reference Data
     * Based on Keputusan Menteri Ketenagakerjaan RI Nomor 65 Tahun 2026.
     */
    public function run(): void
    {
        $legalDecree = 'KEPUTUSAN MENTERI KETENAGAKERJAAN REPUBLIK INDONESIA NOMOR 65 TAHUN 2026';
        $year = 2026;

        $umkData = [
            // D.I. YOGYAKARTA (1-5)
            ['province' => 'D.I. YOGYAKARTA', 'city_district' => 'Kabupaten Gunung Kidul', 'umk_amount' => 2468378],
            ['province' => 'D.I. YOGYAKARTA', 'city_district' => 'Kabupaten Kulon Progo', 'umk_amount' => 2504520],
            ['province' => 'D.I. YOGYAKARTA', 'city_district' => 'Kabupaten Bantul', 'umk_amount' => 2509001],
            ['province' => 'D.I. YOGYAKARTA', 'city_district' => 'Kabupaten Sleman', 'umk_amount' => 2624387],
            ['province' => 'D.I. YOGYAKARTA', 'city_district' => 'Kota Yogyakarta', 'umk_amount' => 2827593],

            // JAWA BARAT (6-32)
            ['province' => 'JAWA BARAT', 'city_district' => 'Kota Banjar', 'umk_amount' => 2361241],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Kuningan', 'umk_amount' => 2369380],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Pangandaran', 'umk_amount' => 2351250],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Ciamis', 'umk_amount' => 2373644],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Garut', 'umk_amount' => 2472227],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Majalengka', 'umk_amount' => 2595368],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Cirebon', 'umk_amount' => 2880798],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kota Cirebon', 'umk_amount' => 2878646],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Tasikmalaya', 'umk_amount' => 2871874],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Indramayu', 'umk_amount' => 2910254],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kota Tasikmalaya', 'umk_amount' => 2980336],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kota Sukabumi', 'umk_amount' => 3192807],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Cianjur', 'umk_amount' => 3316191],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Subang', 'umk_amount' => 3737482],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Sukabumi', 'umk_amount' => 3831926],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Sumedang', 'umk_amount' => 3949856],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Bandung Barat', 'umk_amount' => 3984711],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Bandung', 'umk_amount' => 3972202],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kota Cimahi', 'umk_amount' => 4090568],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kota Bandung', 'umk_amount' => 4737678],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Purwakarta', 'umk_amount' => 5052856],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Bogor', 'umk_amount' => 5161769],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kota Bogor', 'umk_amount' => 5437203],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kota Depok', 'umk_amount' => 5522662],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Bekasi', 'umk_amount' => 5938885],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kabupaten Karawang', 'umk_amount' => 5886853],
            ['province' => 'JAWA BARAT', 'city_district' => 'Kota Bekasi', 'umk_amount' => 5999443],

            // JAWA TENGAH (33-67)
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Banjarnegara', 'umk_amount' => 2327813],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Wonogiri', 'umk_amount' => 2335126],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Sragen', 'umk_amount' => 2337700],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Rembang', 'umk_amount' => 2386305],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Blora', 'umk_amount' => 2345695],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Brebes', 'umk_amount' => 2400350],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Temanggung', 'umk_amount' => 2397000],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Grobogan', 'umk_amount' => 2399186],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Kebumen', 'umk_amount' => 2400000],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Purworejo', 'umk_amount' => 2401962],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kota Magelang', 'umk_amount' => 2429285],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Pemalang', 'umk_amount' => 2433254],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Wonosobo', 'umk_amount' => 2455038],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Pati', 'umk_amount' => 2485000],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Tegal', 'umk_amount' => 2484162],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Purbalingga', 'umk_amount' => 2474722],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Banyumas', 'umk_amount' => 2474599],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Sukoharjo', 'umk_amount' => 2500000],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kota Tegal', 'umk_amount' => 2526510],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Klaten', 'umk_amount' => 2538691],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Boyolali', 'umk_amount' => 2537949],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kota Surakarta', 'umk_amount' => 2570000],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Karanganyar', 'umk_amount' => 2592154],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Magelang', 'umk_amount' => 2607290],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Pekalongan', 'umk_amount' => 2633700],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kota Salatiga', 'umk_amount' => 2698273],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Batang', 'umk_amount' => 2708520],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kota Pekalongan', 'umk_amount' => 2700926],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Jepara', 'umk_amount' => 2756501],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Cilacap', 'umk_amount' => 2773184],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Kudus', 'umk_amount' => 2818585],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Semarang', 'umk_amount' => 2940088],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Kendal', 'umk_amount' => 2992994],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kabupaten Demak', 'umk_amount' => 3122805],
            ['province' => 'JAWA TENGAH', 'city_district' => 'Kota Semarang', 'umk_amount' => 3701709],

            // JAWA TIMUR (68-105)
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Situbondo', 'umk_amount' => 2438962],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Sampang', 'umk_amount' => 2484443],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Bondowoso', 'umk_amount' => 2496886],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Pacitan', 'umk_amount' => 2514892],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Pamekasan', 'umk_amount' => 2528004],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Trenggalek', 'umk_amount' => 2530313],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Bangkalan', 'umk_amount' => 2550274],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Ngawi', 'umk_amount' => 2556815],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Madiun', 'umk_amount' => 2553221],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Ponorogo', 'umk_amount' => 2549876],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Nganjuk', 'umk_amount' => 2564627],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Sumenep', 'umk_amount' => 2553688],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Magetan', 'umk_amount' => 2553866],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Blitar', 'umk_amount' => 2567744],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kota Madiun', 'umk_amount' => 2588794],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Lumajang', 'umk_amount' => 2578320],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Tulungagung', 'umk_amount' => 2628190],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kota Blitar', 'umk_amount' => 2639518],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Kediri', 'umk_amount' => 2651603],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kota Kediri', 'umk_amount' => 2742806],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Banyuwangi', 'umk_amount' => 2989145],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Jember', 'umk_amount' => 3012197],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kota Probolinggo', 'umk_amount' => 3045172],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Probolinggo', 'umk_amount' => 3164526],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Bojonegoro', 'umk_amount' => 2685983],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Lamongan', 'umk_amount' => 3196328],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kota Mojokerto', 'umk_amount' => 3208556],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Tuban', 'umk_amount' => 3229092],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Jombang', 'umk_amount' => 3320770],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kota Pasuruan', 'umk_amount' => 3555301],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kota Batu', 'umk_amount' => 3562484],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kota Malang', 'umk_amount' => 3736101],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Malang', 'umk_amount' => 3802862],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Mojokerto', 'umk_amount' => 5176101],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Pasuruan', 'umk_amount' => 5187681],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Sidoarjo', 'umk_amount' => 5191541],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kabupaten Gresik', 'umk_amount' => 5195401],
            ['province' => 'JAWA TIMUR', 'city_district' => 'Kota Surabaya', 'umk_amount' => 5288796],

            // NUSA TENGGARA TIMUR (106-127)
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Alor', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Belu', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Ende', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Flores Timur', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Kupang', 'umk_amount' => 2532853],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Lembata', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Malaka', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Manggarai', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Manggarai Barat', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Manggarai Timur', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Nagekeo', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Ngada', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Rote Ndao', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Sabu Raijua', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Sikka', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Sumba Barat', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Sumba Barat Daya', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Sumba Tengah', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Sumba Timur', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Timor Tengah Selatan', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kabupaten Timor Tengah Utara', 'umk_amount' => 2455898],
            ['province' => 'NUSA TENGGARA TIMUR', 'city_district' => 'Kota Kupang', 'umk_amount' => 2455898],

            // NUSA TENGGARA BARAT (128-137)
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kabupaten Lombok Barat', 'umk_amount' => 2712254],
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kabupaten Dompu', 'umk_amount' => 2751290],
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kabupaten Lombok Timur', 'umk_amount' => 2744628],
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kabupaten Lombok Utara', 'umk_amount' => 2758221],
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kabupaten Lombok Tengah', 'umk_amount' => 2741526],
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kabupaten Sumbawa', 'umk_amount' => 2747478],
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kabupaten Bima', 'umk_amount' => 2767580],
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kota Bima', 'umk_amount' => 2831163],
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kabupaten Sumbawa Barat', 'umk_amount' => 3136468],
            ['province' => 'NUSA TENGGARA BARAT', 'city_district' => 'Kota Mataram', 'umk_amount' => 3019015],

            // BENGKULU (138-147)
            ['province' => 'BENGKULU', 'city_district' => 'Kabupaten Bengkulu Selatan', 'umk_amount' => 2827250],
            ['province' => 'BENGKULU', 'city_district' => 'Kabupaten Kaur', 'umk_amount' => 2827250],
            ['province' => 'BENGKULU', 'city_district' => 'Kabupaten Kepahiang', 'umk_amount' => 2827250],
            ['province' => 'BENGKULU', 'city_district' => 'Kabupaten Lebong', 'umk_amount' => 2827250],
            ['province' => 'BENGKULU', 'city_district' => 'Kabupaten Rejang Lebong', 'umk_amount' => 2841749],
            ['province' => 'BENGKULU', 'city_district' => 'Kabupaten Seluma', 'umk_amount' => 2827250],
            ['province' => 'BENGKULU', 'city_district' => 'Kabupaten Bengkulu Utara', 'umk_amount' => 2906158],
            ['province' => 'BENGKULU', 'city_district' => 'Kabupaten Bengkulu Tengah', 'umk_amount' => 2945142],
            ['province' => 'BENGKULU', 'city_district' => 'Kota Bengkulu', 'umk_amount' => 3089218],
            ['province' => 'BENGKULU', 'city_district' => 'Kabupaten Mukomuko', 'umk_amount' => 3217086],

            // KALIMANTAN BARAT (148-161)
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Kubu Raya', 'umk_amount' => 3100000],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Mempawah', 'umk_amount' => 3220801],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Sekadau', 'umk_amount' => 3054552],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Kapuas Hulu', 'umk_amount' => 3106259],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Melawi', 'umk_amount' => 3109431],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Sanggau', 'umk_amount' => 3121747],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Sambas', 'umk_amount' => 3202663],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kota Pontianak', 'umk_amount' => 3205220],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Sintang', 'umk_amount' => 3187965],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Landak', 'umk_amount' => 3211256],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Bengkayang', 'umk_amount' => 3252580],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kota Singkawang', 'umk_amount' => 3247387],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Kayong Utara', 'umk_amount' => 3370586],
            ['province' => 'KALIMANTAN BARAT', 'city_district' => 'Kabupaten Ketapang', 'umk_amount' => 3561801],

            // LAMPUNG (162-176)
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Lampung Barat', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Lampung Tengah', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Lampung Timur', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Lampung Utara', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Pesawaran', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Pesisir Barat', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Pringsewu', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Tanggamus', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Tulang Bawang', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Tulang Bawang Barat', 'umk_amount' => 3047734],
            ['province' => 'LAMPUNG', 'city_district' => 'Kota Metro', 'umk_amount' => 3050498],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Way Kanan', 'umk_amount' => 3215764],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Lampung Selatan', 'umk_amount' => 3219609],
            ['province' => 'LAMPUNG', 'city_district' => 'Kabupaten Mesuji', 'umk_amount' => 3227333],
            ['province' => 'LAMPUNG', 'city_district' => 'Kota Bandar Lampung', 'umk_amount' => 3491889],

            // BANTEN (177-184)
            ['province' => 'BANTEN', 'city_district' => 'Kabupaten Lebak', 'umk_amount' => 3330010],
            ['province' => 'BANTEN', 'city_district' => 'Kabupaten Pandeglang', 'umk_amount' => 3360078],
            ['province' => 'BANTEN', 'city_district' => 'Kota Serang', 'umk_amount' => 4665927],
            ['province' => 'BANTEN', 'city_district' => 'Kabupaten Serang', 'umk_amount' => 5178521],
            ['province' => 'BANTEN', 'city_district' => 'Kabupaten Tangerang', 'umk_amount' => 5210377],
            ['province' => 'BANTEN', 'city_district' => 'Kota Tangerang Selatan', 'umk_amount' => 5247870],
            ['province' => 'BANTEN', 'city_district' => 'Kota Tangerang', 'umk_amount' => 5399405],
            ['province' => 'BANTEN', 'city_district' => 'Kota Cilegon', 'umk_amount' => 5469922],

            // SULAWESI TENGAH (185-197)
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Banggai Kepulauan', 'umk_amount' => 3179565],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Banggai Laut', 'umk_amount' => 3179565],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Donggala', 'umk_amount' => 3179565],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Parigi Moutong', 'umk_amount' => 3179565],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Sigi', 'umk_amount' => 3179565],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Tojo Una-Una', 'umk_amount' => 3179565],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Toli-Toli', 'umk_amount' => 3179565],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Banggai', 'umk_amount' => 3179565],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Poso', 'umk_amount' => 3268227],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kota Palu', 'umk_amount' => 3619466],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Buol', 'umk_amount' => 3198109],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Morowali', 'umk_amount' => 4223000],
            ['province' => 'SULAWESI TENGAH', 'city_district' => 'Kabupaten Morowali Utara', 'umk_amount' => 4408209],

            // SUMATERA UTARA (198-230)
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Dairi', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Humbang Hasundutan', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Nias', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Nias Barat', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Nias Selatan', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Nias Utara', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Padang Lawas Utara', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Pakpak Bharat', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Samosir', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Tapanuli Utara', 'umk_amount' => 3307618],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kota Gunungsitoli', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kota Pematang Siantar', 'umk_amount' => 3228949],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kota Tebing Tinggi', 'umk_amount' => 3229958],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kota Binjai', 'umk_amount' => 3367914],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Simalungun', 'umk_amount' => 3351403],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Mandailing Natal', 'umk_amount' => 3355900],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Langkat', 'umk_amount' => 3402892],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Toba', 'umk_amount' => 3404422],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kota Padangsidimpuan', 'umk_amount' => 3416803],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Padang Lawas', 'umk_amount' => 3478237],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Tapanuli Tengah', 'umk_amount' => 3509004],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Asahan', 'umk_amount' => 3531361],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kota Tanjungbalai', 'umk_amount' => 3496857],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Tapanuli Selatan', 'umk_amount' => 3567941],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Serdang Bedagai', 'umk_amount' => 3605983],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Labuhan Batu Utara', 'umk_amount' => 3603415],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Labuhan Batu Selatan', 'umk_amount' => 3690000],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kota Sibolga', 'umk_amount' => 3668668],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Labuhan Batu', 'umk_amount' => 3748181],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Karo', 'umk_amount' => 3843153],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Batu Bara', 'umk_amount' => 3970000],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kabupaten Deli Serdang', 'umk_amount' => 4041543],
            ['province' => 'SUMATERA UTARA', 'city_district' => 'Kota Medan', 'umk_amount' => 4335198],

            // SUMATERA BARAT (231-249)
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Agam', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kota Bukittinggi', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Dharmasraya', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Kepulauan Mentawai', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Lima Puluh Kota', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kota Padang', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kota Padang Panjang', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Padang Pariaman', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kota Pariaman', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Pasaman', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Pasaman Barat', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kota Payakumbuh', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Pesisir Selatan', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kota Sawahlunto', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Sijunjung', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Solok', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kota Solok', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Solok Selatan', 'umk_amount' => 3182955],
            ['province' => 'SUMATERA BARAT', 'city_district' => 'Kabupaten Tanah Datar', 'umk_amount' => 3182955],

            // BALI (250-258)
            ['province' => 'BALI', 'city_district' => 'Kabupaten Bangli', 'umk_amount' => 3207459],
            ['province' => 'BALI', 'city_district' => 'Kabupaten Buleleng', 'umk_amount' => 3207459],
            ['province' => 'BALI', 'city_district' => 'Kabupaten Jembrana', 'umk_amount' => 3207459],
            ['province' => 'BALI', 'city_district' => 'Kabupaten Karangasem', 'umk_amount' => 3207459],
            ['province' => 'BALI', 'city_district' => 'Kabupaten Klungkung', 'umk_amount' => 3207459],
            ['province' => 'BALI', 'city_district' => 'Kabupaten Tabanan', 'umk_amount' => 3287679],
            ['province' => 'BALI', 'city_district' => 'Kabupaten Gianyar', 'umk_amount' => 3316789],
            ['province' => 'BALI', 'city_district' => 'Kota Denpasar', 'umk_amount' => 3499879],
            ['province' => 'BALI', 'city_district' => 'Kabupaten Badung', 'umk_amount' => 3791003],

            // SULAWESI TENGGARA (259-275)
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kota Bau-Bau', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Bombana', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Buton', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Buton Utara', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Buton Selatan', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Buton Tengah', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Kolaka Utara', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Kolaka Timur', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Konawe', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Konawe Selatan', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Konawe Kepulauan', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Muna', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Muna Barat', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Wakatobi', 'umk_amount' => 3306496],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Konawe Utara', 'umk_amount' => 3510506],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kota Kendari', 'umk_amount' => 3516700],
            ['province' => 'SULAWESI TENGGARA', 'city_district' => 'Kabupaten Kolaka', 'umk_amount' => 3688130],

            // SULAWESI BARAT (276-281)
            ['province' => 'SULAWESI BARAT', 'city_district' => 'Kabupaten Majene', 'umk_amount' => 3315934],
            ['province' => 'SULAWESI BARAT', 'city_district' => 'Kabupaten Mamasa', 'umk_amount' => 3315934],
            ['province' => 'SULAWESI BARAT', 'city_district' => 'Kabupaten Mamuju Tengah', 'umk_amount' => 3315934],
            ['province' => 'SULAWESI BARAT', 'city_district' => 'Kabupaten Pasangkayu', 'umk_amount' => 3564798],
            ['province' => 'SULAWESI BARAT', 'city_district' => 'Kabupaten Polewali Mandar', 'umk_amount' => 3327886],
            ['province' => 'SULAWESI BARAT', 'city_district' => 'Kabupaten Mamuju', 'umk_amount' => 3363847],

            // MALUKU (282-292)
            ['province' => 'MALUKU', 'city_district' => 'Kabupaten Buru', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kabupaten Buru Selatan', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kabupaten Kepulauan Aru', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kabupaten Maluku Barat Daya', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kabupaten Maluku Tengah', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kabupaten Maluku Tenggara', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kepulauan Tanimbar', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kabupaten Seram Bagian Barat', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kabupaten Seram Bagian Timur', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kota Tual', 'umk_amount' => 3334490],
            ['province' => 'MALUKU', 'city_district' => 'Kota Ambon', 'umk_amount' => 3381255],

            // GORONTALO (293-298)
            ['province' => 'GORONTALO', 'city_district' => 'Kabupaten Boalemo', 'umk_amount' => 3405144],
            ['province' => 'GORONTALO', 'city_district' => 'Kabupaten Bone Bolango', 'umk_amount' => 3405144],
            ['province' => 'GORONTALO', 'city_district' => 'Kabupaten Gorontalo', 'umk_amount' => 3405144],
            ['province' => 'GORONTALO', 'city_district' => 'Kota Gorontalo', 'umk_amount' => 3405144],
            ['province' => 'GORONTALO', 'city_district' => 'Kabupaten Gorontalo Utara', 'umk_amount' => 3405144],
            ['province' => 'GORONTALO', 'city_district' => 'Kabupaten Pohuwato', 'umk_amount' => 3405144],

            // JAMBI (299-309)
            ['province' => 'JAMBI', 'city_district' => 'Kabupaten Batang Hari', 'umk_amount' => 3471497],
            ['province' => 'JAMBI', 'city_district' => 'Kabupaten Bungo', 'umk_amount' => 3471497],
            ['province' => 'JAMBI', 'city_district' => 'Kabupaten Kerinci', 'umk_amount' => 3471497],
            ['province' => 'JAMBI', 'city_district' => 'Kabupaten Merangin', 'umk_amount' => 3471497],
            ['province' => 'JAMBI', 'city_district' => 'Kota Sungai Penuh', 'umk_amount' => 3471497],
            ['province' => 'JAMBI', 'city_district' => 'Kabupaten Tanjung Jabung Timur', 'umk_amount' => 3486521],
            ['province' => 'JAMBI', 'city_district' => 'Kabupaten Tebo', 'umk_amount' => 3471497],
            ['province' => 'JAMBI', 'city_district' => 'Kabupaten Sarolangun', 'umk_amount' => 3533562],
            ['province' => 'JAMBI', 'city_district' => 'Kabupaten Tanjung Jabung Barat', 'umk_amount' => 3551430],
            ['province' => 'JAMBI', 'city_district' => 'Kabupaten Muaro Jambi', 'umk_amount' => 3651917],
            ['province' => 'JAMBI', 'city_district' => 'Kota Jambi', 'umk_amount' => 3868963],

            // MALUKU UTARA (310-319)
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kabupaten Halmahera Barat', 'umk_amount' => 3510240],
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kabupaten Halmahera Selatan', 'umk_amount' => 3510240],
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kabupaten Halmahera Tengah', 'umk_amount' => 3510240],
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kabupaten Halmahera Timur', 'umk_amount' => 3510240],
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kabupaten Halmahera Utara', 'umk_amount' => 3510240],
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kabupaten Kepulauan Sula', 'umk_amount' => 3510240],
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kabupaten Pulau Morotai', 'umk_amount' => 3510240],
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kabupaten Pulau Taliabu', 'umk_amount' => 3510240],
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kota Tidore Kepulauan', 'umk_amount' => 3510240],
            ['province' => 'MALUKU UTARA', 'city_district' => 'Kota Ternate', 'umk_amount' => 3510240],

            // KALIMANTAN TENGAH (320-333)
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Kapuas', 'umk_amount' => 3710097],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Pulang Pisau', 'umk_amount' => 3701205],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Barito Timur', 'umk_amount' => 3716006],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kota Palangka Raya', 'umk_amount' => 3724678],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Gunung Mas', 'umk_amount' => 3770717],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Kotawaringin Timur', 'umk_amount' => 3756644],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Katingan', 'umk_amount' => 3729767],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Kotawaringin Barat', 'umk_amount' => 3909006],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Sukamara', 'umk_amount' => 3912098],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Lamandau', 'umk_amount' => 3938998],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Murung Raya', 'umk_amount' => 3998046],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Barito Selatan', 'umk_amount' => 4045059],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Seruyan', 'umk_amount' => 4051080],
            ['province' => 'KALIMANTAN TENGAH', 'city_district' => 'Kabupaten Barito Utara', 'umk_amount' => 4093072],

            // KALIMANTAN SELATAN (334-346)
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Balangan', 'umk_amount' => 3725000],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Banjar', 'umk_amount' => 3725000],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kota Banjar Baru', 'umk_amount' => 3843037],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Barito Kuala', 'umk_amount' => 3725000],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Hulu Sungai Selatan', 'umk_amount' => 3725000],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Hulu Sungai Tengah', 'umk_amount' => 3725000],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Hulu Sungai Utara', 'umk_amount' => 3725000],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Tanah Laut', 'umk_amount' => 3725000],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Tapin', 'umk_amount' => 3725000],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Tabalong', 'umk_amount' => 3827935],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kota Banjarmasin', 'umk_amount' => 3855894],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Kotabaru', 'umk_amount' => 3904645],
            ['province' => 'KALIMANTAN SELATAN', 'city_district' => 'Kabupaten Tanah Bumbu', 'umk_amount' => 3736000],

            // RIAU (347-358)
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Indragiri Hilir', 'umk_amount' => 3783053],
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Rokan Hilir', 'umk_amount' => 3780495],
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Kepulauan Meranti', 'umk_amount' => 3780495],
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Rokan Hulu', 'umk_amount' => 3819353],
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Pelalawan', 'umk_amount' => 3894261],
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Kampar', 'umk_amount' => 3898211],
            ['province' => 'RIAU', 'city_district' => 'Kota Pekanbaru', 'umk_amount' => 3998179],
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Siak', 'umk_amount' => 4001327],
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Kuantan Singingi', 'umk_amount' => 3949467],
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Indragiri Hulu', 'umk_amount' => 3988406],
            ['province' => 'RIAU', 'city_district' => 'Kabupaten Bengkalis', 'umk_amount' => 4155318],
            ['province' => 'RIAU', 'city_district' => 'Kota Dumai', 'umk_amount' => 4431175],

            // KALIMANTAN TIMUR (359-368)
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kabupaten Paser', 'umk_amount' => 3776998],
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kota Balikpapan', 'umk_amount' => 3856694],
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kota Samarinda', 'umk_amount' => 3983882],
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kabupaten Kutai Timur', 'umk_amount' => 4067436],
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kabupaten Kutai Kartanegara', 'umk_amount' => 3991797],
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kota Bontang', 'umk_amount' => 3799480],
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kabupaten Kutai Barat', 'umk_amount' => 4231617],
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kabupaten Mahakam Ulu', 'umk_amount' => 3762431],
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kabupaten Penajam Paser Utara', 'umk_amount' => 4181134],
            ['province' => 'KALIMANTAN TIMUR', 'city_district' => 'Kabupaten Berau', 'umk_amount' => 4391338],

            // KALIMANTAN UTARA (369-373)
            ['province' => 'KALIMANTAN UTARA', 'city_district' => 'Kabupaten Nunukan', 'umk_amount' => 3845251],
            ['province' => 'KALIMANTAN UTARA', 'city_district' => 'Kabupaten Bulungan', 'umk_amount' => 3900396],
            ['province' => 'KALIMANTAN UTARA', 'city_district' => 'Kabupaten Tana Tidung', 'umk_amount' => 3870800],
            ['province' => 'KALIMANTAN UTARA', 'city_district' => 'Kabupaten Malinau', 'umk_amount' => 4040073],
            ['province' => 'KALIMANTAN UTARA', 'city_district' => 'Kota Tarakan', 'umk_amount' => 4742169],

            // PAPUA BARAT DAYA (374-379)
            ['province' => 'PAPUA BARAT DAYA', 'city_district' => 'Kabupaten Maybrat', 'umk_amount' => 3766000],
            ['province' => 'PAPUA BARAT DAYA', 'city_district' => 'Kabupaten Raja Ampat', 'umk_amount' => 3766000],
            ['province' => 'PAPUA BARAT DAYA', 'city_district' => 'Kabupaten Sorong', 'umk_amount' => 3766000],
            ['province' => 'PAPUA BARAT DAYA', 'city_district' => 'Kota Sorong', 'umk_amount' => 3766000],
            ['province' => 'PAPUA BARAT DAYA', 'city_district' => 'Kabupaten Sorong Selatan', 'umk_amount' => 3766000],
            ['province' => 'PAPUA BARAT DAYA', 'city_district' => 'Kabupaten Tambrauw', 'umk_amount' => 3766000],

            // PAPUA BARAT (380-386)
            ['province' => 'PAPUA BARAT', 'city_district' => 'Kabupaten Fakfak', 'umk_amount' => 3841000],
            ['province' => 'PAPUA BARAT', 'city_district' => 'Kabupaten Kaimana', 'umk_amount' => 3841000],
            ['province' => 'PAPUA BARAT', 'city_district' => 'Kabupaten Manokwari', 'umk_amount' => 3841000],
            ['province' => 'PAPUA BARAT', 'city_district' => 'Kabupaten Manokwari Selatan', 'umk_amount' => 3841000],
            ['province' => 'PAPUA BARAT', 'city_district' => 'Kabupaten Pegunungan Arfak', 'umk_amount' => 3841000],
            ['province' => 'PAPUA BARAT', 'city_district' => 'Kabupaten Teluk Bintuni', 'umk_amount' => 3841000],
            ['province' => 'PAPUA BARAT', 'city_district' => 'Kabupaten Teluk Wondama', 'umk_amount' => 3841000],

            // KEPULAUAN RIAU (387-393)
            ['province' => 'KEPULAUAN RIAU', 'city_district' => 'Kabupaten Lingga', 'umk_amount' => 3879520],
            ['province' => 'KEPULAUAN RIAU', 'city_district' => 'Kota Tanjung Pinang', 'umk_amount' => 3879520],
            ['province' => 'KEPULAUAN RIAU', 'city_district' => 'Kabupaten Natuna', 'umk_amount' => 3879520],
            ['province' => 'KEPULAUAN RIAU', 'city_district' => 'Kabupaten Karimun', 'umk_amount' => 4241935],
            ['province' => 'KEPULAUAN RIAU', 'city_district' => 'Kabupaten Kepulauan Anambas', 'umk_amount' => 4279851],
            ['province' => 'KEPULAUAN RIAU', 'city_district' => 'Kabupaten Bintan', 'umk_amount' => 4583221],
            ['province' => 'KEPULAUAN RIAU', 'city_district' => 'Kota Batam', 'umk_amount' => 5357982],

            // SULAWESI SELATAN (394-417)
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Bantaeng', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Barru', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Bone', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Bulukumba', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Enrekang', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Gowa', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Jeneponto', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Luwu', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Luwu Timur', 'umk_amount' => 3961166],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Luwu Utara', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Maros', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kota Palopo', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Pangkajene dan Kepulauan', 'umk_amount' => 4032248],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kota Parepare', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Pinrang', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Kepulauan Selayar', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Sidenreng Rappang', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Sinjai', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Soppeng', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Takalar', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Tana Toraja', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Toraja Utara', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kabupaten Wajo', 'umk_amount' => 3921088],
            ['province' => 'SULAWESI SELATAN', 'city_district' => 'Kota Makassar', 'umk_amount' => 4148719],

            // SUMATERA SELATAN (418-434)
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Empat Lawang', 'umk_amount' => 3942963],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Lahat', 'umk_amount' => 4041420],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kota Lubuk Linggau', 'umk_amount' => 3942963],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Ogan Ilir', 'umk_amount' => 3942963],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Ogan Komering Ilir', 'umk_amount' => 3942963],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Ogan Komering Ulu', 'umk_amount' => 3942963],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Ogan Komering Ulu Selatan', 'umk_amount' => 3942963],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Penukal Abab Lematang Ilir', 'umk_amount' => 3942963],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Musi Rawas Utara', 'umk_amount' => 4047385],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kota Pagar Alam', 'umk_amount' => 3942963],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kota Prabumulih', 'umk_amount' => 3942963],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Banyuasin', 'umk_amount' => 3976492],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Ogan Komering Ulu Timur', 'umk_amount' => 3993876],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Musi Banyuasin', 'umk_amount' => 4039054],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Musi Rawas', 'umk_amount' => 4058812],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kabupaten Muara Enim', 'umk_amount' => 4178363],
            ['province' => 'SUMATERA SELATAN', 'city_district' => 'Kota Palembang', 'umk_amount' => 4192837],

            // ACEH (435-457)
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Barat', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Barat Daya', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Besar', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Jaya', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Selatan', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Singkil', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Tengah', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Tenggara', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Timur', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Utara', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Bener Meriah', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Bireuen', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Gayo Lues', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kota Langsa', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kota Lhokseumawe', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Nagan Raya', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Pidie', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Pidie Jaya', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kota Sabang', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Simeulue', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kota Subulussalam', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kabupaten Aceh Tamiang', 'umk_amount' => 3932552],
            ['province' => 'ACEH', 'city_district' => 'Kota Banda Aceh', 'umk_amount' => 3932552],

            // SULAWESI UTARA (458-472)
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kota Bitung', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Bolaang Mongondow', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Bolaang Mongondow Selatan', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Bolaang Mongondow Timur', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Bolaang Mongondow Utara', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Kepulauan Sangihe', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Kepulauan Siau Tagulandang Biaro', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Kepulauan Talaud', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kota Kotamobagu', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Minahasa', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Minahasa Selatan', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Minahasa Tenggara', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kabupaten Minahasa Utara', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kota Tomohon', 'umk_amount' => 4002630],
            ['province' => 'SULAWESI UTARA', 'city_district' => 'Kota Manado', 'umk_amount' => 4022017],

            // KEPULAUAN BANGKA BELITUNG (473-479)
            ['province' => 'KEPULAUAN BANGKA BELITUNG', 'city_district' => 'Kabupaten Bangka', 'umk_amount' => 4035000],
            ['province' => 'KEPULAUAN BANGKA BELITUNG', 'city_district' => 'Kabupaten Bangka Barat', 'umk_amount' => 4035000],
            ['province' => 'KEPULAUAN BANGKA BELITUNG', 'city_district' => 'Kabupaten Bangka Selatan', 'umk_amount' => 4035000],
            ['province' => 'KEPULAUAN BANGKA BELITUNG', 'city_district' => 'Kabupaten Bangka Tengah', 'umk_amount' => 4035000],
            ['province' => 'KEPULAUAN BANGKA BELITUNG', 'city_district' => 'Kabupaten Belitung', 'umk_amount' => 4035000],
            ['province' => 'KEPULAUAN BANGKA BELITUNG', 'city_district' => 'Kabupaten Belitung Timur', 'umk_amount' => 4035000],
            ['province' => 'KEPULAUAN BANGKA BELITUNG', 'city_district' => 'Kota Pangkal Pinang', 'umk_amount' => 4035000],

            // PAPUA (480-488)
            ['province' => 'PAPUA', 'city_district' => 'Kabupaten Biak Numfor', 'umk_amount' => 4436283],
            ['province' => 'PAPUA', 'city_district' => 'Kabupaten Jayapura', 'umk_amount' => 4436283],
            ['province' => 'PAPUA', 'city_district' => 'Kabupaten Keerom', 'umk_amount' => 4436283],
            ['province' => 'PAPUA', 'city_district' => 'Kabupaten Kepulauan Yapen', 'umk_amount' => 4436283],
            ['province' => 'PAPUA', 'city_district' => 'Kabupaten Mamberamo Raya', 'umk_amount' => 4436283],
            ['province' => 'PAPUA', 'city_district' => 'Kabupaten Sarmi', 'umk_amount' => 4436283],
            ['province' => 'PAPUA', 'city_district' => 'Kabupaten Supiori', 'umk_amount' => 4436283],
            ['province' => 'PAPUA', 'city_district' => 'Kabupaten Waropen', 'umk_amount' => 4436283],
            ['province' => 'PAPUA', 'city_district' => 'Kota Jayapura', 'umk_amount' => 4436283],

            // PAPUA TENGAH (489-496)
            ['province' => 'PAPUA TENGAH', 'city_district' => 'Kabupaten Deiyai', 'umk_amount' => 4285848],
            ['province' => 'PAPUA TENGAH', 'city_district' => 'Kabupaten Dogiyai', 'umk_amount' => 4285848],
            ['province' => 'PAPUA TENGAH', 'city_district' => 'Kabupaten Intan Jaya', 'umk_amount' => 4285848],
            ['province' => 'PAPUA TENGAH', 'city_district' => 'Kabupaten Nabire', 'umk_amount' => 4285848],
            ['province' => 'PAPUA TENGAH', 'city_district' => 'Kabupaten Paniai', 'umk_amount' => 4285848],
            ['province' => 'PAPUA TENGAH', 'city_district' => 'Kabupaten Puncak', 'umk_amount' => 4285848],
            ['province' => 'PAPUA TENGAH', 'city_district' => 'Kabupaten Puncak Jaya', 'umk_amount' => 4285848],
            ['province' => 'PAPUA TENGAH', 'city_district' => 'Kabupaten Mimika', 'umk_amount' => 5005678],

            // PAPUA SELATAN (497-500)
            ['province' => 'PAPUA SELATAN', 'city_district' => 'Kabupaten Asmat', 'umk_amount' => 4508100],
            ['province' => 'PAPUA SELATAN', 'city_district' => 'Kabupaten Boven Digoel', 'umk_amount' => 4508100],
            ['province' => 'PAPUA SELATAN', 'city_district' => 'Kabupaten Mappi', 'umk_amount' => 4508100],
            ['province' => 'PAPUA SELATAN', 'city_district' => 'Kabupaten Merauke', 'umk_amount' => 4508100],

            // PAPUA PEGUNUNGAN (501-508)
            ['province' => 'PAPUA PEGUNUNGAN', 'city_district' => 'Kabupaten Jayawijaya', 'umk_amount' => 4508714],
            ['province' => 'PAPUA PEGUNUNGAN', 'city_district' => 'Kabupaten Lanny Jaya', 'umk_amount' => 4508714],
            ['province' => 'PAPUA PEGUNUNGAN', 'city_district' => 'Kabupaten Mamberamo Tengah', 'umk_amount' => 4508714],
            ['province' => 'PAPUA PEGUNUNGAN', 'city_district' => 'Kabupaten Nduga', 'umk_amount' => 4508714],
            ['province' => 'PAPUA PEGUNUNGAN', 'city_district' => 'Kabupaten Pegunungan Bintang', 'umk_amount' => 4508714],
            ['province' => 'PAPUA PEGUNUNGAN', 'city_district' => 'Kabupaten Tolikara', 'umk_amount' => 4508714],
            ['province' => 'PAPUA PEGUNUNGAN', 'city_district' => 'Kabupaten Yalimo', 'umk_amount' => 4508714],
            ['province' => 'PAPUA PEGUNUNGAN', 'city_district' => 'Kabupaten Yahukimo', 'umk_amount' => 4508714],

            // DAERAH KHUSUS IBUKOTA JAKARTA (509-514)
            ['province' => 'DKI JAKARTA', 'city_district' => 'Kota Administrasi Jakarta Barat', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'Kota Administrasi Jakarta Pusat', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'Kota Administrasi Jakarta Selatan', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'Kota Administrasi Jakarta Timur', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'Kota Administrasi Jakarta Utara', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'Kabupaten Administrasi Kepulauan Seribu', 'umk_amount' => 5729876],

            // Also add alias short names for Jakarta districts for smart matching
            ['province' => 'DKI JAKARTA', 'city_district' => 'Jakarta Barat', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'Jakarta Pusat', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'Jakarta Selatan', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'Jakarta Timur', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'Jakarta Utara', 'umk_amount' => 5729876],
            ['province' => 'DKI JAKARTA', 'city_district' => 'DKI Jakarta', 'umk_amount' => 5729876],
        ];

        foreach ($umkData as $data) {
            UmkReference::updateOrCreate(
                [
                    'city_district' => $data['city_district'],
                ],
                [
                    'province' => $data['province'],
                    'umk_amount' => $data['umk_amount'],
                    'year' => $year,
                    'legal_decree' => $legalDecree,
                ]
            );
        }
    }
}
